
Calibrations.o: Calibrations.cpp Calibrations.h 
	g++ -c `root-config --cflags` Calibrations.cpp

CutsManager.o : CutsManager.cpp CutsManager.h TupleVars.hpp
	g++ -c -I../CodesforAnalysis/Parte2/ `root-config --cflags` CutsManager.cpp
