#WARNING: this file is automatically generated with generate_amsvar.sh
#          for questions paolo.zuccon@pg.infn.it
 
 
export AMSBASE=/opt/exp_software/ams/AMSsoft_modified/
#export AMSBASE=/opt/exp_software/ams/AMSsoft_afs/

export AMSSYS=linux_slc6_gcc64
#export ROOTSYS=$AMSBASE/$AMSSYS/root_v5.27ams/
export ROOTSYS=$AMSBASE/$AMSSYS/root_v5.34ams/
#export ECALBDT=1

#pre B550
#export ROOTSYS=$AMSBASE/$AMSSYS/root_v5.27ams_shift/

export CERN=$AMSBASE/$AMSSYS/
export CERN_LEVEL=2005/
export CERN_ROOT=$CERN/$CERN_LEVEL
export CERNDIR=$CERN/$CERN_LEVEL
export AMSLIB=$CERNDIR

#export AMSDataDir=/opt/exp_software/ams/AMSDataDir_afs/
#export AMSDataDir=/storage/gpfs_superb/ams/Offline/AMSDataDir/
export AMSDataDir=/opt/exp_software/ams/AMSDataDir/

ls $AMSDataDir 
# used to trigger automount

export PATH=$ROOTSYS/bin:$CERN_ROOT/bin:/opt/intel/Compiler/11.1/073/bin/intel64:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:/opt/intel/Compiler/11.1/073/lib/intel64
#export LD_LIBRARY_PATH=/opt/exp_software/ams/additional_libs/lib64/:$LD_LIBRARY_PATH
export CLHEP_BASE_DIR=$AMSBASE/$AMSSYS/CLHEP
export CLHEP_INCLUDE_DIR=$AMSBASE/$AMSSYS/CLHEP/include
export CLHEP_LIB_DIR=$AMSBASE/$AMSSYS/CLHEP/lib
export G4INSTALL=$AMSBASE/$AMSSYS/geant4_ams
 
 
export G4SYSTEM=Linux-g++
 
 
# Environment variables needed to find geant4 data files:
#
# Data for neutron scattering processes,
#    distributed in a separate tar file, then placed under data
export NeutronHPCrossSections=$AMSBASE/share/geant4/data/G4NDL
#
#  Nuclear Photon evaporation data,
#    distributed with the source files under data
export G4LEVELGAMMADATA=$AMSBASE/share/geant4/data/PhotonEvaporation
#
# Data for radiative decay hadronic processes under data,
#    distributed in a separate tar file
export G4RADIOACTIVEDATA=$AMSBASE/share/geant4/data/RadiativeDecay
#
# Data for low energy electromagnetic processes,
#    distributed in a separate tar file, then placed under data
export G4LEDATA=$AMSBASE/share/geant4/data/G4EMLOW
#
# Data for elastic scattering processes,
#    distributed in a separate tar file, then placed under data
export G4ELASTICDATA=$AMSBASE/share/geant4/data/G4ELASTIC
 
 

export AMSP=1
export PGTRACK=1
export ECALBDT=1
export AMSSRC=/storage/gpfs_ams/ams/users/macrispo/AMSRoot/lib/AMS/
export AMSWD=/home/AMS/fdimicco/fdimicco/lib/
export AMSGeoDir=$AMSSRC/display/ams02/
export CVSROOT=:ext:fdimicco@lxplus.cern.ch:/afs/cern.ch/ams/Offline/CVS
export CVS_RSH=ssh
export NOCASTOR=1

#export LD_LIBRARY_PATH=/storage/gpfs_ams/ams/users/mgraziani/amsrootmaura-code/AMSRoot/lib/:$LD_LIBRARY_PATH



export PATH=$AMSSRC/bin:$PATH
export PATH=$AMSSRC/exe/linuxx8664gcc5.34/:$PATH
export AMSLIBso=$AMSSRC/lib/linuxx8664gcc5.34/ntuple_slc4_PG.so

export NOCASTOR=1 #otehrwise AMSDisplay can be not compiling
export NOXROOTD=1 #added my Matt
export NORFIOD=1 #added by Matt
#uncomment the following 3 lines to set CASTOR debug mode access
#setenv RFIO_TRACE 3
#setenv STAGER_TRACE 3
#setenv XrdSecDEBUG 10

#TrdQT
export AMS_ACQT_INTERFACE=1
export ACROOTSOFTWARE=$AMSDataDir/v5.00/TRD
export ACROOTLOOKUPS=$ACROOTSOFTWARE/acroot/data



export LD_LIBRARY_PATH=$AMSBASE/$AMSSYS/xrootd/lib64/:$LD_LIBRARY_PATH
